### ISSUE TITLE
A few errors

### ISSUE THREAD

**Issue by mamereu** [Tnifey/arango#2]
I tried the README example and got the following:
`
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ArangoCollection,
----------------------
    at https://raw.githubusercontent.com/Tnifey/arango/master/src/aql.ts:6:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  GeneratedAqlQuery,
----------------------
    at https://raw.githubusercontent.com/Tnifey/arango/master/src/aql.ts:7:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  AqlLiteral,
----------------------
    at https://raw.githubusercontent.com/Tnifey/arango/master/src/aql.ts:8:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  AqlLiteralValueType,
----------------------
    at https://raw.githubusercontent.com/Tnifey/arango/master/src/aql.ts:9:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  AqlValue,
----------------------
    at https://raw.githubusercontent.com/Tnifey/arango/master/src/aql.ts:10:3

`

**Comment by Tnifey** [comment]
yea, if I remember correctly, it was running well on deno <=1.1.x (without type checking  :O) and arango 3.6.x
I've refactored this. It should work on the latest version now.
